ros_impedance_controller:
  type: ros_impedance_controller/Controller
  joints:
    - joint1
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
    
  gains:
    joint1: {p: 30.0, i: 0.0, d: 1.0}
    joint2: {p: 30.0, i: 0.0, d: 1.0}
    joint3: {p: 30.0, i: 0.0, d: 1.0}
    joint4: {p: 30.0, i: 0.0, d: 1.0}
    joint5: {p: 30.0, i: 0.0, d: 1.0}
    joint6: {p: 30.0, i: 0.0, d: 1.0}

 
  home: #default
    joint1:  0.0
    joint2:  0.0
    joint3:  0.0
    joint4:  0.0
    joint5:  0.0
    joint6:  0.0
    
